using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.Xml.Linq;
using RCNet.Extensions;
using RCNet.XmlTools;
using RCNet.Neural.Network.SM.Preprocessing.Reservoir.Space3D;
using RCNet.Neural.Network.SM.Preprocessing.Reservoir.Neuron.Predictor;

namespace RCNet.Neural.Network.SM.Preprocessing.Reservoir
{
    /// <summary>
    /// Configuration of an input unit associated with the input field
    /// </summary>
    [Serializable]
    public class InputUnitSettings : RCNetBaseSettings
    {
        //Constants
        /// <summary>
        /// Name of the associated xsd type
        /// </summary>
        public const string XsdTypeName = "NPResInstanceInputUnitType";
        //Default values
        /// <summary>
        /// Default length of the spike-train representation of analog value
        /// </summary>
        public const int DefaultSpikeTrainLength = 8;
        /// <summary>
        /// Default analog firing threshold
        /// </summary>
        public const double DefaultAnalogFiringThreshold = 0.00125d;
        /// <summary>
        /// Default analog neuron predictors
        /// </summary>
        public const bool DefaultAnalogNeuronPredictors = false;
        /// <summary>
        /// Default spiking neuron predictors
        /// </summary>
        public const bool DefaultSpikingNeuronPredictors = false;

        /// <summary>
        /// Name of the input field
        /// </summary>
        public string InputFieldName { get; }

        /// <summary>
        /// Length of the spike-train representation of analog value
        /// </summary>
        public int SpikeTrainLength { get; }

        /// <summary>
        /// Analog firing threshold
        /// </summary>
        public double AnalogFiringThreshold { get; }

        /// <summary>
        /// Specifies if to allow predictors generated by input analog neuron
        /// </summary>
        public bool AnalogNeuronPredictors;

        /// <summary>
        /// Specifies if to allow predictors generated by input spiking neurons
        /// </summary>
        public bool SpikingNeuronPredictors;

        /// <summary>
        /// Input entry point coordinates within the 3D space
        /// </summary>
        public CoordinatesSettings CoordinatesCfg { get; }

        /// <summary>
        /// Input unit connections
        /// </summary>
        public InputUnitConnsSettings ConnsCfg { get; }

        /// <summary>
        /// Configuration of the predictors
        /// </summary>
        public PredictorsSettings PredictorsCfg { get; }

        //Constructors
        /// <summary>
        /// Creates an itialized instance.
        /// </summary>
        /// <param name="inputFieldName">Name of the input field</param>
        /// <param name="connsCfg">Input unit connections</param>
        /// <param name="spikeTrainLength">Length of the spike-train representation of analog value</param>
        /// <param name="analogFiringThreshold">Analog firing threshold</param>
        /// <param name="analogNeuronPredictors">Specifies if to allow predictors generated by input analog neuron</param>
        /// <param name="spikingNeuronPredictors">Specifies if to allow predictors generated by input spiking neurons</param>
        /// <param name="predictorsCfg">Configuration of the predictors</param>
        /// <param name="coordinatesCfg">Input entry point coordinates within the 3D space</param>
        public InputUnitSettings(string inputFieldName,
                                 InputUnitConnsSettings connsCfg,
                                 int spikeTrainLength = DefaultSpikeTrainLength,
                                 double analogFiringThreshold = DefaultAnalogFiringThreshold,
                                 bool analogNeuronPredictors = DefaultAnalogNeuronPredictors,
                                 bool spikingNeuronPredictors = DefaultSpikingNeuronPredictors,
                                 PredictorsSettings predictorsCfg = null,
                                 CoordinatesSettings coordinatesCfg = null
                                 )
        {
            InputFieldName = inputFieldName;
            ConnsCfg = (InputUnitConnsSettings)connsCfg.DeepClone();
            SpikeTrainLength = spikeTrainLength;
            AnalogFiringThreshold = analogFiringThreshold;
            AnalogNeuronPredictors = analogNeuronPredictors;
            SpikingNeuronPredictors = spikingNeuronPredictors;
            PredictorsCfg = predictorsCfg == null ? null : (PredictorsSettings)predictorsCfg.DeepClone();
            CoordinatesCfg = coordinatesCfg == null ? new CoordinatesSettings() : (CoordinatesSettings)coordinatesCfg.DeepClone();
            Check();
            return;
        }

        /// <summary>
        /// The deep copy constructor.
        /// </summary>
        /// <param name="source">Source instance</param>
        public InputUnitSettings(InputUnitSettings source)
            :this(source.InputFieldName, source.ConnsCfg, source.SpikeTrainLength, source.AnalogFiringThreshold,
                 source.AnalogNeuronPredictors, source.SpikingNeuronPredictors, source.PredictorsCfg, source.CoordinatesCfg)
        {
            return;
        }

        /// <summary>
        /// Creates an initialized instance from the given xml element.
        /// </summary>
        /// <param name="elem">
        /// Xml data containing the settings.
        /// Content of xml element is always validated against the xml schema.
        /// </param>
        public InputUnitSettings(XElement elem)
        {
            //Validation
            XElement settingsElem = Validate(elem, XsdTypeName);
            //Parsing
            InputFieldName = settingsElem.Attribute("inputFieldName").Value;
            SpikeTrainLength = int.Parse(settingsElem.Attribute("spikeTrainLength").Value, CultureInfo.InvariantCulture);
            AnalogFiringThreshold = double.Parse(settingsElem.Attribute("analogFiringThreshold").Value, CultureInfo.InvariantCulture);
            AnalogNeuronPredictors = bool.Parse(settingsElem.Attribute("analogNeuronPredictors").Value);
            SpikingNeuronPredictors = bool.Parse(settingsElem.Attribute("spikingNeuronPredictors").Value);
            ConnsCfg = new InputUnitConnsSettings(settingsElem.Elements("connections").First());
            XElement coordinatesElem = settingsElem.Elements("coordinates").FirstOrDefault();
            CoordinatesCfg = coordinatesElem == null ? new CoordinatesSettings() : new CoordinatesSettings(coordinatesElem);
            //Predictors
            XElement predictorsSettingsElem = settingsElem.Elements("predictors").FirstOrDefault();
            if (predictorsSettingsElem != null)
            {
                PredictorsCfg = new PredictorsSettings(predictorsSettingsElem);
            }
            Check();
            return;
        }

        //Properties
        /// <summary>
        /// Checks if settings are default
        /// </summary>
        public bool IsDefaultSpikeTrainLength { get { return (SpikeTrainLength == DefaultSpikeTrainLength); } }

        /// <summary>
        /// Checks if settings are default
        /// </summary>
        public bool IsDefaultAnalogFiringThreshold { get { return (AnalogFiringThreshold == DefaultAnalogFiringThreshold); } }

        /// <summary>
        /// Checks if settings are default
        /// </summary>
        public bool IsDefaultAnalogNeuronPredictors { get { return (AnalogNeuronPredictors == DefaultAnalogNeuronPredictors); } }

        /// <summary>
        /// Checks if settings are default
        /// </summary>
        public bool IsDefaultSpikingNeuronPredictors { get { return (SpikingNeuronPredictors == DefaultSpikingNeuronPredictors); } }

        /// <summary>
        /// Identifies settings containing only default values
        /// </summary>
        public override bool ContainsOnlyDefaults { get { return false; } }

        //Methods
        /// <summary>
        /// Checks validity
        /// </summary>
        private void Check()
        {
            if(InputFieldName.Length == 0)
            {
                throw new Exception($"Empty InputFieldName.");
            }
            if (SpikeTrainLength < 1 || SpikeTrainLength > 32)
            {
                throw new Exception($"Invalid SpikeTrainLength {SpikeTrainLength.ToString(CultureInfo.InvariantCulture)}. SpikeTrainLength must be GE to 1 and LE to 32.");
            }
            if (AnalogFiringThreshold < 0 || AnalogFiringThreshold >= 1)
            {
                throw new Exception($"Invalid AnalogFiringThreshold {AnalogFiringThreshold.ToString(CultureInfo.InvariantCulture)}. AnalogFiringThreshold must be GE to 0 and LT 1.");
            }
            return;
        }

        /// <summary>
        /// Creates the deep copy instance of this instance
        /// </summary>
        public override RCNetBaseSettings DeepClone()
        {
            return new InputUnitSettings(this);
        }

        /// <summary>
        /// Generates xml element containing the settings.
        /// </summary>
        /// <param name="rootElemName">Name to be used as a name of the root element.</param>
        /// <param name="suppressDefaults">Specifies if to ommit optional nodes having set default values</param>
        /// <returns>XElement containing the settings</returns>
        public override XElement GetXml(string rootElemName, bool suppressDefaults)
        {
            XElement rootElem = new XElement(rootElemName, new XAttribute("inputFieldName", InputFieldName));
            if (!suppressDefaults || !IsDefaultSpikeTrainLength)
            {
                rootElem.Add(new XAttribute("spikeTrainLength", SpikeTrainLength.ToString(CultureInfo.InvariantCulture)));
            }
            if (!suppressDefaults || !IsDefaultAnalogFiringThreshold)
            {
                rootElem.Add(new XAttribute("analogFiringThreshold", AnalogFiringThreshold.ToString(CultureInfo.InvariantCulture)));
            }
            if (!suppressDefaults || !IsDefaultAnalogNeuronPredictors)
            {
                rootElem.Add(new XAttribute("analogNeuronPredictors", AnalogNeuronPredictors.ToString(CultureInfo.InvariantCulture).ToLowerInvariant()));
            }
            if (!suppressDefaults || !IsDefaultSpikingNeuronPredictors)
            {
                rootElem.Add(new XAttribute("spikingNeuronPredictors", SpikingNeuronPredictors.ToString(CultureInfo.InvariantCulture).ToLowerInvariant()));
            }
            if (!suppressDefaults || !CoordinatesCfg.ContainsOnlyDefaults)
            {
                rootElem.Add(CoordinatesCfg.GetXml(suppressDefaults));
            }
            rootElem.Add(ConnsCfg.GetXml(suppressDefaults));
            if (PredictorsCfg != null && !PredictorsCfg.ContainsOnlyDefaults)
            {
                rootElem.Add(PredictorsCfg.GetXml(suppressDefaults));
            }
            Validate(rootElem, XsdTypeName);
            return rootElem;
        }

        /// <summary>
        /// Generates default named xml element containing the settings.
        /// </summary>
        /// <param name="suppressDefaults">Specifies if to ommit optional nodes having set default values</param>
        /// <returns>XElement containing the settings</returns>
        public override XElement GetXml(bool suppressDefaults)
        {
            return GetXml("inputUnit", suppressDefaults);
        }

    }//InputUnitSettings

}//Namespace

